apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ffqdz73ll-go 
  janus-idp.io/tekton: ffqdz73ll-go
  backstage.io/kubernetes-id: ffqdz73ll-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ffqdz73ll-go
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml