apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ffqdz73ll-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ffqdz73ll-go 
  name: ffqdz73ll-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ffqdz73ll-go 
